config/routes.rb
Blue::Application.routes.draw do

  resources :events

  resources :specialists

  resources :reservations

  resources :orders

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => 'home#index'

  devise_for :users

  resources :users

  resources :carts do
    resources :carts_products

  end

  resources :products

  get 'home/about_us'

  get 'home/index'

end

app/models/specialist.rb
class Specialist < ActiveRecord::Base
  attr_accessible :date

  has_many :specialists_products, :primary_key => "id", :foreign_key => "specialist_id"
  has_many :products, :through => :specialists_products


end

app/controllers/specialists_controller.rb
class SpecialistsController < ApplicationController
  before_filter :authenticate_user!, :only => [:index, :new, :edit, :create, :update, :destroy]
  before_filter :get_cart
  # GET /specialists
  # GET /specialists.json
  def index
    @specialists = Specialist.all
    authorize! :new, @user, :message => 'Not authorized as an administrator.'
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @specialists }
    end
  end

  # GET /specialists/1
  # GET /specialists/1.json
  def show
    @specialist = Specialist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @specialist }
    end
  end

  # GET /specialists/new
  # GET /specialists/new.json
  def new
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @specialist = Specialist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @specialist }
    end
  end

  # GET /specialists/1/edit
  def edit
    authorize! :index, @user, :message => 'Not authorized as an administrator.'

    @specialist = Specialist.find(params[:id])
  end

  # POST /specialists
  # POST /specialists.json
  def create
    authorize! :index, @user, :message => 'Not authorized as an administrator.'

    @specialist = Specialist.new(params[:specialist])

    respond_to do |format|
      if @specialist.save
        format.html { redirect_to @specialist, notice: 'Specialist was successfully created.' }
        format.json { render json: @specialist, status: :created, location: @specialist }
      else
        format.html { render action: "new" }
        format.json { render json: @specialist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /specialists/1
  # PUT /specialists/1.json
  def update
    authorize! :index, @user, :message => 'Not authorized as an administrator.'

    @specialist = Specialist.find(params[:id])

    respond_to do |format|
      if @specialist.update_attributes(params[:specialist])
        format.html { redirect_to @specialist, notice: 'Specialist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @specialist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specialists/1
  # DELETE /specialists/1.json
  def destroy
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @specialist = Specialist.find(params[:id])
    @specialist.destroy

    respond_to do |format|
      format.html { redirect_to specialists_url }
      format.json { head :no_content }
    end
  end

  private
  def get_cart
    @cart = current_cart
  end
end

app/helpers/specialists_helper.rb
module SpecialistsHelper
end

app/views/specialists/_form.html.erb
<%= simple_form_for(@specialist) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/specialists/edit.html.erb
<% provide :title, "Edit Specialist" %>
<h1>Editing specialist</h1>

<%= render 'form' %>
<%= link_to 'BACK', :back %>

app/views/specialists/index.html.erb
<% provide :title, "All Specialist" %>
<h1>Listing specialists</h1>

<table class="table">
  <tr>
    <th>Special ID</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @specialists.each do |specialist| %>
  <tr>
    <td><%= link_to specialist.id, specialist, :class => "btn" %></td>
    <td><%= link_to 'Edit', edit_specialist_path(specialist), :class => 'btn' %></td>
    <td><%= link_to 'DELETE', specialist, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Specialist', new_specialist_path %>
<%= link_to 'BACK', :back %>

app/views/specialists/new.html.erb
<% provide :title, "New Specialist" %>
<h1>New specialist</h1>

<%= render 'form' %>

<%= link_to 'Back', specialists_path %>

app/views/specialists/show.html.erb
<% provide :title, "Today Specialist" %>
<h1>Today Special</h1>
<% specialists_products = @specialist.specialists_products %>

<div class="row">
  <div class="span8">
        <% specialists_products.each do |specialists_product| %>
            <% product = specialists_product.product %>

            <div class="media">
              <%= link_to cl_image_tag(product.picture, :width => 200, :height => 180, :crop => :scale, :class => "media-object pull-left"), product_path(product) %>
              <div class="media-body">
                <h2 class="media-heading"><%= product.name %></h2>
                <%= product.price %>
                <div class="media">
                  <%= form_tag "/carts/#{@cart.id}/carts_products", :method => :post do %>
                      <%= hidden_field_tag :product_id, product.id %>
                      <%= select_tag :quantity, options_for_select(1..5) %>
                      <%= submit_tag "Add To Cart", :class => "btn btn-success btn-large" %>
                  <% end %>

                </div>
              </div>
            </div>
        <% end %>


  </div>
</div>
<%= link_to 'BACK', :back, :class => "btn" %>