config/routes.rb
Blue::Application.routes.draw do

  resources :events

  resources :specialists

  resources :reservations

  resources :orders

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => 'home#index'

  devise_for :users

  resources :users

  resources :carts do
    resources :carts_products

  end

  resources :products

  get 'home/about_us'

  get 'home/index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  attr_accessible :users_id
  has_many :carts_products, :foreign_key => "cart_id", :class_name => "CartsProduct", :dependent => :destroy
  has_many :products, :through => :carts_products
  has_one :order
  has_one :reservation, :foreign_key => :cart_id
  belongs_to :user, :foreign_key => "users_id", :primary_key => "id"

  def line_item
    CartsProduct.select("id, carts_id, products_id, sum(quantity) as quantity").where("carts_id = ?", id).group("products_id")
  end

  def total_price
    carts_products.to_a.sum(&:full_price)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_filter :authenticate_user!, :only => :index
  before_filter :get_cart, :only => [:new, :create]
  # GET /carts
  # GET /carts.json
  def index
    authorize! :new, @user, :message => 'Not authorized as an administrator.'
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :no_content }
    end
  end

  private
  def get_cart
    @cart = current_cart
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def get_email(user)
    if user.nil?
      email = "unregister user"
    else
      email = user.email
    end
    return email
  end

end

app/views/carts/_cart.html.erb
<table>
  <thead>
  <tr>
    <td></td>
    <td>Name</td>
    <td></td>
  </tr>
  </thead>
  <% carts_products.each do |carts_product| %>
      <tr>
        <% product = carts_product.product %>
        <td><div class="thumbnail"><%= cl_image_tag(product.picture, :width => 200, :height => 180, :crop => :scale) %></div></td>
        <td><%= product.name %><td>

        <td><%= carts_product.quantity %></td>
        <td><%= link_to 'edit', edit_cart_carts_products_path(carts_product) %></td>
        <td></td>
      </tr>
  <% end %>

</table>

app/views/carts/_form.html.erb
<%= simple_form_for(@cart) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :users_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<% provide :title, "Edit My Cart" %>
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<% provide :title, "All Carts" %>
<h1>Listing carts</h1>

<table>
  <tr>
    <th>Users</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= get_email(cart.user) %></td>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<% provide :title, "New Cart" %>
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% provide :title, "My Cart" %>
<% carts_products = @cart.carts_products %>
<div class="row">
  <div class="span8">
    <% if carts_products %>
        <% carts_products.each do |carts_product| %>
            <% product = carts_product.product %>

            <div class="media">
              <%= link_to cl_image_tag(product.picture, :width => 200, :height => 180, :crop => :scale, :class => "media-object pull-left"), product_path(product) %>
              <div class="media-body">
                <h2 class="media-heading"><%= product.name %></h2>
                <p>Quantity: <%= carts_product.quantity %></p>
                <div class="media">
                  <%= link_to 'DELETE', [@cart, carts_product], method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-warning" %>
                  <%= simple_form_for([@cart,carts_product], :html => {:class => "form-inline"}) do |f| %>
                      <%= f.input :quantity, :collection => 1..5 %>
                      <%= f.submit "update", :class => "btn" %>
                  <% end %>
                </div>
              </div>
            </div>
        <% end %>

    <% end %>

  </div>

  <div class="span4">
    <div class="well sidebar-nav" >
      <ul class="nav nav-list">


        <li class="nav-header">Total money</li>
        <li>
          <%= "Total Order #{@cart.total_price}" %>
        </li>
        <li class="nav-header">Action</li>
        <li>
          <%= link_to 'Check OUT', new_order_path %>
        </li>
        <li>
          <%= link_to 'Continuing Shopping', products_path, :class => "btn-link" %>
        </li>
        <li>
          <%= link_to 'Clear Cart', @cart, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
    </div>

  </div>
</div>