config/routes.rb
Blue::Application.routes.draw do

  resources :events

  resources :specialists

  resources :reservations

  resources :orders

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => 'home#index'

  devise_for :users

  resources :users

  resources :carts do
    resources :carts_products

  end

  resources :products

  get 'home/about_us'

  get 'home/index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  attr_accessible :users_id
  has_many :carts_products, :foreign_key => "cart_id", :class_name => "CartsProduct", :dependent => :destroy
  has_many :products, :through => :carts_products
  has_one :order
  has_one :reservation, :foreign_key => :cart_id
  belongs_to :user, :foreign_key => "users_id", :primary_key => "id"

  def line_item
    CartsProduct.select("id, carts_id, products_id, sum(quantity) as quantity").where("carts_id = ?", id).group("products_id")
  end

  def total_price
    carts_products.to_a.sum(&:full_price)
  end
end

app/models/carts_product.rb
class CartsProduct < ActiveRecord::Base
  attr_accessible :cart_id, :product_id, :quantity
  belongs_to :cart, :foreign_key => "product_id"
  belongs_to :product, :foreign_key => "product_id"

  def full_price
    (quantity * product.price).round
  end

  private

  def set_default
    self.quantity = 1 unless self.quantity
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :name, :order_id, :requirement, :user_id
  belongs_to :user
  belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessor :card_number, :card_verification, :address1, :address2, :city, :state, :zip_code, :name
  attr_accessible :card_number, :card_verification, :card_type, :card_expires_on, :first_name, :last_name, :cart_id,
                  :address1, :address2,:city, :state, :zip_code, :name, :user_address_attributes, :order_type_id, :user_id

  belongs_to :order_type
  has_one :user_address, :foreign_key => "order_id"
  accepts_nested_attributes_for :user_address
  belongs_to :user
  belongs_to :cart, :foreign_key => "cart_id", :primary_key => "id"
  has_one :event
  validate :validate_card, :on => "create"
  validates_presence_of :card_number, :card_expires_on, :address1, :city, :state, :zip_code, :first_name, :last_name



  def purchase
    response = GATEWAY.purchase(price_in_cents, credit_card)
    response.success?
  end

  def price_in_cents
    (cart.total_price*100).round
  end

  private

  def purchase_options
    {
        :ip => ip_address,
        :billing_address => {
            :name     => name,
            :address1 => address1,
            :city     => city,
            :state    => state,
            :country  => "US",
            :zip      => zip_code
        }
    }
  end

  def validate_card
    unless credit_card.valid?
      credit_card.errors.full_messages.each do |message|
        errors[:base] << message
      end
    end
  end

  def credit_card
    @credit_card ||= ActiveMerchant::Billing::CreditCard.new(
        :type               => card_type,
        :number             => card_number,
        :verification_value => card_verification,
        :month              => card_expires_on.month,
        :year               => card_expires_on.year,
        :first_name         => first_name,
        :last_name          => last_name
    )
  end
end

app/models/order_type.rb
class OrderType < ActiveRecord::Base
  has_many :orders, :foreign_key => "order_type_id"
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :picture, :price, :product_type

  has_many :carts_products, :foreign_key => "product_id"
  has_many :carts, :through => :carts_products

  has_one :product_types, :foreign_key => "product_id"
  has_many :specialists_products, :foreign_key => "product_id", :primary_key => "id"
  has_many :specialists, :through => :specialists_products


  def self.my_find type
    where("type = ?", type)
  end
end

app/models/product_types.rb
class ProductTypes < ActiveRecord::Base
  attr_accessible :name
  belongs_to :product
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :name, :number_of_tables, :order_id, :phone, :start_date, :user_id, :cart_id

  belongs_to :cart, :foreign_key => "cart_id"
  belongs_to :user
  validates_presence_of :name, :number_of_tables, :start_date, :phone
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/specialist.rb
class Specialist < ActiveRecord::Base
  attr_accessible :date

  has_many :specialists_products, :primary_key => "id", :foreign_key => "specialist_id"
  has_many :products, :through => :specialists_products


end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  validates_presence_of :email
  validates_uniqueness_of :email, :case_sensitive => false
  has_many :reservations
  has_many :addresses, :class_name => "UserAddress", :foreign_key => "user_id"
  has_many :orders
  has_many :events
end

app/models/user_address.rb
class UserAddress < ActiveRecord::Base
  attr_accessible :name, :address1, :address2, :city, :state, :zip

  belongs_to :user
  belongs_to :order, :foreign_key => "order_id"
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors(resource)
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def get_email(user)
    if user.nil?
      email = "unregister user"
    else
      email = user.email
    end
    return email
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_ie.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- .btn-navbar is used as the toggle for collapsed navbar content -->
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</a>
<div class="nav-collapse collapse" >
  <ul class="nav">
    <li class="<%= 'active' if current_page?(root_path) %>">
      <%= link_to 'HOME', root_path %>
    </li>
    <li class="<%= 'active' if current_page?(products_path) %>">
      <%= link_to 'SHOPPING', products_path %>
    </li>
    <% if @cart %>
      <li class="<%= 'active' if current_page?(cart_path(@cart)) %>">
        <%= link_to 'SHOPPING CART', cart_path(@cart) %>
      </li>
    <% end %>
    <% if user_signed_in? %>
      <li class="<%= 'active' if current_page?(new_event_path) %>">
        <%= link_to 'NEW EVENT', new_event_path %>
      </li>
    <% end %>
    <li class="<%= 'active' if current_page?(new_reservation_path) %>">
      <%= link_to 'RESERVATION', new_reservation_path %>
    </li>
  </ul>
  <ul class="nav nav-tabs pull-right">
    <% if user_signed_in? %>
        <li>
          <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
        </li>
    <% else %>
        <li>
          <%= link_to('Login', new_user_session_path)  %>
        </li>
    <% end %>
    <% if user_signed_in? %>
        <li class="<%= 'active' if current_page?(edit_user_registration_path) %>">
          <%= link_to('Edit account', edit_user_registration_path) %>
        </li>
        <li class="<%= 'active' if current_page?(current_user) %>">
          <%= link_to 'MY ACCOUNT', current_user %>
        </li>
        <% if current_user.has_role? :admin %>
            <li class="<%= 'active' if current_page?(users_path) %>">
              <%= link_to('Admin', users_path) %>
            </li>
        <% end %>
    <% else %>
        <li class="<%= 'active' if current_page?(new_user_registration_path) %>">
          <%= link_to('Sign up', new_user_registration_path)  %>
        </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="author" content>
  <title><%= content_for?(:title) ? yield(:title) : "App_Name" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "App_Name" %>">
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
  <%= render 'layouts/ie' %>
</head>
<body>
<header class="navbar navbar-fixed-top">
  <nav class="navbar-inner">
    <div class="container">
      <%= render 'layouts/navigation' %>
    </div>
  </nav>
</header>
<div id="wrap" role="main" >
  <div class="container">
    <div class="content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </div>
</div>
<footer id="footer">
  <div class="container">
    <p class="muted credit">Powered by <a href="https://github.com/wangalrebt/blue-667">Wang</a>
    <p><%= link_to 'About Us', home_about_us_path %>
  </div>
</footer>
</body>
</html>